### ISSUE TITLE
Failing to install slap

### ISSUE THREAD

**Issue by orschiro** [Filirom1/npm2arch#7]
Hi there,

I am struggling installing [slap](https://github.com/slap-editor/slap). According to their README, the following command should install it:

```
$ sudo npm install -g slap
```

Thus I tried `npm2archinstall` but it fails with the following error:

```
~ ❯ npm2archinstall slap
==> ERROR: Missing package() function in /tmp/npm2archinstall-6aab90e8-be45-46dd-9dcf-76e185e3eab6/PKGBUILD

path.js:360
        throw new TypeError('Arguments to path.join must be strings');
              ^
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at /usr/lib/node_modules/npm2arch/lib/createPkg.coffee:90:35
    at Object.oncomplete (fs.js:108:15)
```

I don't know what to do with the error message. Can you help me?

Many thanks!

Robert

**Comment by Undeterminant** [comment]
It appears to be a problem with how `makepkg` errors are resolved. The latest version of pacman finally turned a missing `package()` function from a warning to an error, so, it falls through code that doesn't handle the error properly.

I think that I fixed it in 0e6b96b, but let me know if you have problems!

**Comment by Undeterminant** [comment]
Oh, that's why it doesn't work. I've fixed it and uploaded a new version to the AUR and NPM.

**Comment by orschiro** [comment]
@Undeterminant 

Many thanks for your fix! I will try it as soon as I am able to build the latest version from the AUR.

See my comment in the AUR.

**Comment by orschiro** [comment]
version `0.1.18` allowed me to install slap.

Many thanks!

Robert
